#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files | \
  ctags-universal -L - --file-scope=yes -if0=yes --line-directives=yes --fields=+lS -f"$$.tags"
  #ctags --tag-relative -L - -f"$$.tags" --languages=-javascript,sql
mv "$$.tags" "tags"
