#!/usr/bin/env sh

# Set background
setbg &

# Bind keys
#sxhkd &
#polybar > ~/.logs/polybar.log 2&>1 &

# Set keyboard layouts and shortcuts
setxkbmap -layout us,ru,il -variant ,phonetic, -option 'grp:alt_shift_toggle'
# Set keyboard layout per window
kbdd

xset r rate 300 50 &	# Speed xrate up
xset s 300 5 &   # Dim screen after 5 minutes. Lock after another 5 seconds
xset dpms 600 1800 14400 &   # Standby after 10 minutes. Suspend after another 20. Shutdown after another 3.5 hours.
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- env XSECURELOCK_SAVER=saver_xscreensaver lock &
unclutter &		# Remove mouse when idle
picom -b
dunst &			# dunst for notifications
#mpd             # music player daemon
mpris-proxy &   # Forward midi controls from BT devides to music player
redshift &      # lower blue light during night

. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
/usr/bin/polkit-dumb-agent > ~/.logs/polkit.log 2&>1 &
#eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
#export SSH_AUTH_SOCK
