#!/usr/bin/env sh

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

export TZ="Asia/Jerusalem"

# Credit to https://superuser.com/a/39995/1536362
pathappend() {
    REQ_DIR=$1
    if [ -d "$REQ_DIR" ] && [[ ":$PATH:" != *":$REQ_DIR:"* ]]; then
        PATH="${PATH:+"$PATH:"}$REQ_DIR"
    fi
}

pathprepend() {
    REQ_DIR=$1
    if [ -d "$REQ_DIR" ] && [[ ":$PATH:" != *":$REQ_DIR:"* ]]; then
        PATH="$REQ_DIR${PATH:+":$PATH"}"
    fi
}

# Set PATH so it includes user's private bin if it exists
DIRS_TO_PREPEND="
    $HOME/.local/bin \
    $HOME/.local/usr/bin \
    $HOME/.local/usr/local/bin \
    "

for dir in $DIRS_TO_PREPEND; do
    pathprepend $dir
done

# Ruby exports
if [ -d $HOME/gems ]; then
    export GEM_HOME=$HOME/gems
    pathprepend $HOME/gems/bin
fi

# Add Doom Emacs to PATH
if [ -d $HOME/.emacs.d/bin ]; then
    pathprepend $HOME/.emacs.d/bin/
fi

WSL=`grep microsoft /proc/version`
if [ -n "$WSL" ]; then
    export DISPLAY=$(grep "nameserver 172" /etc/resolv.conf | cut -d " " -f 2):0
    export NOTES=/mnt/c/Users/$USER/Nextcloud-BC/Notes/
else
    export NOTES=$HOME/Nextcloud/Notes/
fi
export LIBGL_ALWAYS_INDIRECT=1

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# Adds `~/.local/bin/` and all subdirectories to $PATH
#export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
export EDITOR="vim"
export VISUAL="nvim"
export TERMINAL="termite"
#export BROWSER="qutebrowser"
#export BROWSER="firefox"
export BROWSER="chromium"
export PAGER="less"
export READER="zathura"
export FILE="vifm-start"
export WM="bspwm"
if [ -f ~/.config/conky/conky.conf ]; then
    export CONKY_WIDTH=$(grep 'maximum_width' ~/.config/conky/conky.conf | cut -d'=' -f2)
fi

# less/man colors
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"; a="${a%_}"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"; a="${a%_}"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"; a="${a%_}"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"; a="${a%_}"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"; a="${a%_}"

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
else
    # Since this is sources anyway inside bashrc
    if [ -f "$HOME/.cargo/env" ]; then
        . "$HOME/.cargo/env"
    fi
fi

# Start graphical server if WM not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x "$WM" >/dev/null && exec startx
