#!/usr/bin/env sh

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

export TZ="Asia/Jerusalem"

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/.local/usr/bin" ] ; then
    PATH="$HOME/.local/usr/bin:$PATH"
fi

if [ -d "$HOME/.local/usr/local/bin" ] ; then
    export PATH=$HOME/.local/usr/local/bin:$PATH
fi

# Ruby exports
if [ -d $HOME/gems ]; then
    export GEM_HOME=$HOME/gems
    export PATH=$HOME/gems/bin:$PATH
fi

# Add Doom Emacs to PATH
if [ -d $HOME/.emacs.d/bin ]; then
    export PATH=$HOME/.emacs.d/bin/:$PATH
fi

# Add local binaries and scripts to the PATH
export PATH=$HOME/.local/usr/local/bin:$PATH

WSL=`grep microsoft /proc/version`
if [ -n "$WSL" ]; then
    export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
    export NOTES=/mnt/c/Users/$USER/Nextcloud-BC/Notes/
else
    export NOTES=$HOME/Nextcloud/Notes/
fi
export LIBGL_ALWAYS_INDIRECT=1

# Adds `~/.local/bin/` and all subdirectories to $PATH
#export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
export EDITOR="vim"
export VISUAL="nvim"
export TERMINAL="termite"
#export BROWSER="qutebrowser"
#export BROWSER="firefox"
export BROWSER="chromium"
export PAGER="less"
export READER="zathura"
export FILE="vifm-start"
export WM="bspwm"
if [ -f ~/.config/conky/conky.conf ]; then
    export CONKY_WIDTH=$(grep 'maximum_width' ~/.config/conky/conky.conf | cut -d'=' -f2)
fi

# less/man colors
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"; a="${a%_}"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"; a="${a%_}"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"; a="${a%_}"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"; a="${a%_}"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"; a="${a%_}"

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# Start graphical server if WM not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x "$WM" >/dev/null && exec startx
